

server:
  port: 80
  servlet:
    context-path: /wygl
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jxkc?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: cat281375
    # 指定德鲁伊连接池.
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  # 扫描映射文件
  mapper-locations: mapper/*.xml
  # 配置别名
  type-aliases-package: com.neny.wygl.bean
  configuration:
    # 开启驼峰映射.
    map-underscore-to-camel-case: true
logging:
  file:
    path: ./logs
  pattern:
    level: info